
from opencadd.databases.klifs import setup_remote

from selectivity_pcm.paths import PROJECT_ROOT

OUTPUT_FILE = (
    PROJECT_ROOT
    / "examples"
    / "rock2"
    / "kinase_pockets.py"
)

TARGETS = {
    "ROCK2": "4L6Q",
    "ROCK1": "3V8S",
    "CSNK2A2": "3OFM",
    "AURKA": "4DEE",
    "STK3": "5DH3",
}


def main():
    session = setup_remote()

    pockets = {}

    for target, pdb_id in TARGETS.items():
        print()
        print("=" * 60)
        print(f"Fetching {target}")
        print(f"  PDB: {pdb_id}")

        structures = session.structures.by_structure_pdb_id(
            pdb_id
        )

        if structures.empty:
            raise ValueError(
                f"No KLIFS structures found for PDB {pdb_id}"
            )

        print(
            f"  KLIFS records: {len(structures)}"
        )

        print(
            "  Available structure columns:"
        )
        print(
            structures.columns.tolist()
        )

        if "structure.qualityscore" in structures.columns:
            structures = structures.sort_values(
                "structure.qualityscore",
                ascending=False,
            )

        structure = structures.iloc[0]

        structure_id = int(
            structure["structure.klifs_id"]
        )

        print(
            f"  KLIFS structure ID: {structure_id}"
        )

        sequence = str(structure["structure.pocket"]
                       )

        if len(sequence) != 85:
            raise ValueError(
                f"Expected 85 KLIFS pocket residues, "
                f"got {len(sequence)} for {target}: {sequence}"
             )
        
        pocket = session.pockets.by_structure_klifs_id(
            structure_id
        )

        print(
            f"  Pocket rows: {len(pocket)}"
        )

        print(
            f"  Pocket length: {len(sequence)}"
        )
        print(
            f"  Pocket sequence: {sequence}"
        )

        pockets[target] = {
            "pdb": pdb_id,
            "structure_klifs_id": structure_id,
            "pocket_sequence": sequence,
        }

    OUTPUT_FILE = (
        PROJECT_ROOT
        / "examples"
        / "rock2"
        / "kinase_pockets.py"
    )

    with OUTPUT_FILE.open(
        "w",
        encoding="utf-8",
    ) as handle:
        handle.write(
            '"""KLIFS-aligned kinase pocket sequences.\n\n'
        )
        handle.write(
            "Generated by scripts/fetch_klifs_pockets.py.\n"
        )
        handle.write(
            "Each pocket contains 85 aligned KLIFS positions.\n"
        )
        handle.write(
            '"""\n\n'
        )

        handle.write(
            "KINASE_POCKETS = {\n"
        )

        for target, data in pockets.items():
            handle.write(
                f'    "{target}": {{\n'
            )

            handle.write(
                f'        "pdb": "{data["pdb"]}",\n'
            )

            handle.write(
                f'        "structure_klifs_id": '
                f'{data["structure_klifs_id"]},\n'
            )

            handle.write(
                f'        "pocket_sequence": '
                f'"{data["pocket_sequence"]}",\n'
            )

            handle.write(
                "    },\n"
            )

        handle.write(
            "}\n"
        )

    print()
    print("=" * 60)
    print(f"\nSaved to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()