"""KLIFS-aligned kinase pocket sequences.

Generated by scripts/fetch_klifs_pockets.py.
Each pocket contains 85 aligned KLIFS positions.
"""

KINASE_POCKETS = {
    "ROCK2": {
        "pdb": "4L6Q",
        "structure_klifs_id": 1810,
        "pocket_sequence": "KVIGRGAFGEVQLYAMKLLFFWEERDIMAFANPWVVQLFYAYMVMEYMPGGDLVNLMSNAIHSMGLIHRDVKPDNMLLLADFGTC",
    },
    "ROCK1": {
        "pdb": "3V8S",
        "structure_klifs_id": 2692,
        "pocket_sequence": "KVIGRGAFGEVQLYAMKLLFFWEERDIMAFANPWVVQLFYAYMVMEYMPGGDLVNLMSNAIHSMGFIHRDVKPDNMLLLADFGTC",
    },
    "CSNK2A2": {
        "pdb": "3OFM",
        "structure_klifs_id": 2728,
        "pocket_sequence": "RKLGRGKYSEVFEVVVKILKIKREVKILENLRTNIIKLIDTALVFEYIN_NTDFKQLYQYCHSKGIMHRDVKPHNVMILIDWGLA",
    },
    "AURKA": {
        "pdb": "4DEE",
        "structure_klifs_id": 1952,
        "pocket_sequence": "RPLGKGKFGNVYLLALKVLQLRREVEIQSHLRPNILRLYGYYLILEYAPLGTVYRELQKYCHSKRVIHRDIKPENLLLIADFGWS",
    },
    "STK3": {
        "pdb": "5DH3",
        "structure_klifs_id": 7028,
        "pocket_sequence": "EKLGEGSYGSVFKVAIKQVEIIKEISIMQQCDPYVVKYYGSWIVMEYCGAGSVSDIIRLYLHFMRKIHRDIKAGNILLLADFGVA",
    },
}
